# Generated by Django 5.1.4 on 2024-12-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='game_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='location',
        ),
    ]
