# Generated by Django 5.1.4 on 2025-01-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default=0, max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(default='city', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
