# Generated by Django 5.1.4 on 2025-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='connecting_in_date',
            field=models.CharField(default='no connection'),
        ),
        migrations.AddField(
            model_name='flight',
            name='connecting_location_in',
            field=models.CharField(default='no connection', max_length=255),
        ),
        migrations.AddField(
            model_name='flight',
            name='connecting_location_out',
            field=models.CharField(default='no connection', max_length=255),
        ),
        migrations.AddField(
            model_name='flight',
            name='connecting_out_date',
            field=models.CharField(default='no connection'),
        ),
    ]
