# Generated by Django 5.1.4 on 2025-01-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
