# Generated by Django 5.1.4 on 2025-01-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_team_abbreviation_alter_team_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
