# Generated by Django 5.1.4 on 2024-12-31 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=155, unique=True)),
                ('event_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
